import { Sudoku } from "../../../domain/entity/sudoku";
import {
  FixedSudokuSquare,
  OpenSudokuSquare,
} from "../../../domain/entity/sudoku-square";

export const sampleSudoku1 = new Sudoku(
  "09b0f4b0-2b45-4beb-89e4-f60cc66cc39a",
  [
    [
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(6),
      new FixedSudokuSquare(3),
      new FixedSudokuSquare(4),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new OpenSudokuSquare(),
      new FixedSudokuSquare(4),
      new FixedSudokuSquare(1),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(7),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(7),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(3),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new FixedSudokuSquare(6),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(2),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new OpenSudokuSquare(),
      new FixedSudokuSquare(2),
      new FixedSudokuSquare(9),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(6),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(4),
    ],
    [
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(9),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(5),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(1),
      new OpenSudokuSquare(),
    ],
    [
      new FixedSudokuSquare(9),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(2),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(6),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new FixedSudokuSquare(1),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(3),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
    [
      new FixedSudokuSquare(2),
      new FixedSudokuSquare(5),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new FixedSudokuSquare(1),
      new FixedSudokuSquare(7),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
      new OpenSudokuSquare(),
    ],
  ]
);
